---
name: main

defaults:
  run:
    # In addition to GitHub's default, also abort when using undefined variables, and output individual commands.
    # For the default, see
    # <https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell>.
    shell: 'bash --noprofile --norc -euo pipefail -x {0}'

on:
  push:
    branches:
      - master
    tags:
      - '*'

  pull_request:
    branches:
      - '**'

  schedule:
    - # Every Monday at 11:10 UTC.
      cron: "10 11 * * 1"

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        variant:
          - php-version: '5.6'
            composer-file: 'composer-legacy-php.json'

          - php-version: '7.0'
            composer-file: 'composer-legacy-php.json'

          - php-version: '7.1'
            composer-file: 'composer-legacy-php.json'

          - php-version: '7.2'
            composer-file: 'composer-legacy-php.json'

          - php-version: '7.3'
            composer-file: 'composer.json'

          - php-version: '7.4'
            composer-file: 'composer.json'

          - php-version: '8.0'
            composer-file: 'composer.json'

          - php-version: '8.1'
            composer-file: 'composer.json'

    name: >-
      Test and lint
      with PHP ${{ matrix.variant.php-version }}
      using Composer dependencies as specified in ${{ matrix.variant.composer-file }}

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
        with:
          persist-credentials: false      

      - name: 'Setup PHP ${{ matrix.variant.php-version }} and install Composer'
        uses: shivammathur/setup-php@d37cc3048580de06099c81ded417530716a0d7ab
        with:
          php-version: ${{ matrix.variant.php-version }}
          tools: composer

      - name: 'Validate Composer file ${{ matrix.variant.composer-file }}'
        run: |
          composer --no-interaction validate \
            --no-check-all \
            --no-check-publish \
            --no-check-version \
            -- \
            "$COMPOSER"
        env:
          COMPOSER: '${{ matrix.variant.composer-file }}'

      - name: 'Install dependencies as specified in ${{ matrix.variant.composer-file }}'
        run: |
          for i in $(seq 1 3)
          do
            if timeout 600 composer --no-interaction install
            then
              # Successfully installed dependencies with Composer.
              exit 0
            fi
          done

          echo 'ERROR: Trying to install dependencies with Composer failed multiple times.' >&2
          exit 1
        env:
          COMPOSER: '${{ matrix.variant.composer-file }}'

      - name: 'Run tests'
        run: |
          ./vendor/bin/phpunit --verbose --coverage-text --coverage-clover=coverage.clover
